
use btl_csdl_ptit;

CREATE TABLE KhoanPhiTrongNam (
	TenNamHoc VARCHAR(20) NOT NULL,
    TenKhoanPhi VARCHAR(100) NOT NULL,
    SoTienPhaiDong DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (TenNamHoc, TenKhoanPhi),
    FOREIGN KEY (TenNamHoc) REFERENCES NamHoc (TenNamHoc)
);


CREATE TABLE LanDongPhi (
    MaGiaoDich INT AUTO_INCREMENT PRIMARY KEY,
    TenKhoanPhi VARCHAR(100) NOT NULL,
    TenNamHoc VARCHAR(20) NOT NULL,
    TenLop VARCHAR(20) NOT NULL,
    MaHS VARCHAR(20) NOT NULL,
    ThoiGianDong DATE NOT NULL,
    SoTienDaDong DECIMAL(12,2) NOT NULL,
    ConNo DECIMAL(12,2) NOT NULL,
	FOREIGN KEY (TenNamHoc, TenLop, MaHS) REFERENCES HocSinh(TenNamHoc, TenLop, MaHS)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (TenKhoanPhi, TenNamHoc) REFERENCES KhoanPhiTrongNam(TenKhoanPhi, TenNamHoc)
        ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE LopHoc (
    TenNamHoc VARCHAR(20) NOT NULL,
    TenLop VARCHAR(50) NOT NULL,
    MaNS_G VARCHAR(20) NOT NULL,
    SiSo SMALLINT,
    PhongHocChinh VARCHAR(20),
    PRIMARY KEY (TenNamHoc, TenLop),
    FOREIGN KEY (MaNS_G) REFERENCES GiaoVien (MaNS_G)
);

CREATE TABLE HocSinh (
	TenNamHoc VARCHAR(20) NOT NULL,
    TenLop VARCHAR(50) NOT NULL,
    MaHS VARCHAR(20) NOT NULL,
    HoDem VARCHAR(20),
    TenRieng VARCHAR(20),
    NgaySinh DATE,
    GioiTinh ENUM('Nam', 'Nu') DEFAULT 'Nam',
    DiaChi VARCHAR(50),
    HoTenPhuHuynh VARCHAR (100),
    SDTPhuHuynh VARCHAR (20),
    TrangThaiHocTap VARCHAR(20),
    PRIMARY KEY (TenNamHoc, TenLop, MaHS),
    FOREIGN KEY (TenNamHoc, TenLop) REFERENCES LopHoc(TenNamHoc, TenLop)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE ThamGiaBanTru (
    TenNamHoc VARCHAR(20) NOT NULL,
    TenLop VARCHAR(50) NOT NULL,
    MaHS VARCHAR(20) NOT NULL,
    NgayAn DATE NOT NULL,
    PRIMARY KEY (TenNamHoc, TenLop, MaHS, NgayAn),
    FOREIGN KEY (TenNamHoc, TenLop, MaHS) REFERENCES HocSinh(TenNamHoc, TenLop, MaHS)
        ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (NgayAN) REFERENCES LanAN(NgayAn)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE LanAn(
	NgayAn DATE PRIMARY KEY
)