DROP DATABASE IF EXISTS school;
CREATE DATABASE school;
USE school;

CREATE TABLE NhanSu (
    MaNS VARCHAR(20) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh VARCHAR(10),
    DiaChi VARCHAR(255),
    Email VARCHAR(100),
    TrangThaiLamViec VARCHAR(50),
    CCCD VARCHAR(12),
    NgayVaoLam DATE
);

CREATE TABLE BangLuong (
    MaNS VARCHAR(20),
    NgayNhanLuong DATE,
    LuongCoBan DECIMAL(18, 2),
    Thuong DECIMAL(18, 2),
    PhuCap DECIMAL(18, 2),
    KhauTru DECIMAL(18, 2),
    PRIMARY KEY(MaNS, NgayNhanLuong),
    FOREIGN KEY (MaNS) REFERENCES NhanSu(MaNS) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE NhanSuSDT (
	 MaNS VARCHAR(20),
     SDT VARCHAR(20),
     PRIMARY KEY (MaNS, SDT),
     FOREIGN KEY (MaNS) REFERENCES NhanSu (MaNS)
);

CREATE TABLE ViTriCV_MoTaCV (
    ViTriCongViec VARCHAR(100),
    MoTaCongViec VARCHAR(100),
    PRIMARY KEY (ViTriCongViec)
);

CREATE TABLE CanBoNhanVien (
    MaNS_C VARCHAR(20) PRIMARY KEY,
    ViTriCongViec VARCHAR(100),
    FOREIGN KEY (MaNS_C) REFERENCES NhanSu(MaNS)  ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ViTriCongViec) REFERENCES ViTriCV_MoTaCV(ViTriCongViec)
);

CREATE TABLE GiaoVien (
    MaNS_G VARCHAR(20) PRIMARY KEY,
    TrinhDoChuyenMon VARCHAR(100),
    PhongBan VARCHAR(100),
    ThamNienNghe INT,
    FOREIGN KEY (MaNS_G) REFERENCES NhanSu(MaNS) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE NamHoc (
    TenNamHoc VARCHAR(20) PRIMARY KEY,
    NgayBatDau DATE,
    NgayKetThuc DATE
);

CREATE TABLE KhoanPhiTrongNam (
    TenNamHoc VARCHAR(20),
    TenKhoanPhi VARCHAR(100),
    SoTienPhaiDong BIGINT,
    PRIMARY KEY (TenNamHoc, TenKhoanPhi),
    FOREIGN KEY (TenNamHoc) REFERENCES NamHoc(TenNamHoc)  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE LopHoc (
	TenNamHoc VARCHAR(20),
    TenLop VARCHAR(10),
    MaNS_G VARCHAR(20),
    SiSo INT,
    PhongHocChinh VARCHAR(10),
    PRIMARY KEY (TenNamHoc, TenLop),
    FOREIGN KEY (MaNS_G) REFERENCES GiaoVien(MaNS_G),
    FOREIGN KEY (TenNamHoc) REFERENCES NamHoc(TenNamHoc)
);

CREATE TABLE HocSinh (
    MaHS INT,
    TenNamHoc VARCHAR(20),
    TenLop VARCHAR(10),
    HoDem VARCHAR(50),
    TenRieng VARCHAR(50),
    NgaySinh DATE,
    GioiTinh VARCHAR(10),
    DiaChi VARCHAR(255),
    HoTenPhuHuynh VARCHAR(100),
    SDTPhuHuynh VARCHAR(15),
    TrangThaiHocTap VARCHAR(50),
    PRIMARY KEY(TenNamHoc, TenLop, MaHS),
    FOREIGN KEY (TenNamHoc, TenLop) REFERENCES LopHoc(TenNamHoc, TenLop) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE LanDongPhi (
    MaGiaoDich VARCHAR(20) PRIMARY KEY, 
    ThoiGianDong DATE,
    SoTienDaDong BIGINT,
    ConNo BIGINT,
    TenKhoanPhi VARCHAR(100),
    TenNamHoc VARCHAR(20),
    TenLop VARCHAR(10),
    MaHS INT,
    FOREIGN KEY (TenNamHoc, TenLop, MaHS) REFERENCES HocSinh(TenNamHoc, TenLop, MaHS) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (TenNamHoc, TenKhoanPhi) REFERENCES KhoanPhiTrongNam(TenNamHoc, TenKhoanPhi)
);

CREATE TABLE LanAn (
	NgayAn DATE PRIMARY KEY
);

CREATE TABLE LanAnMonAn (
	NgayAn DATE,
    MonAn VARCHAR(50),
    FOREIGN KEY (NgayAn) REFERENCES LanAn(NgayAn)  ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (NgayAn, MonAn)
);

CREATE TABLE ThamGiaBanTru (
    TenNamHoc VARCHAR(20),
    TenLop VARCHAR(10),
    MaHS INT,
    NgayAn DATE,
    MaNS_G VARCHAR(20),
    PRIMARY KEY (TenNamHoc, TenLop, MaHS, NgayAn),
    FOREIGN KEY (TenNamHoc, TenLop, MaHS) REFERENCES HocSinh(TenNamHoc, TenLop, MaHS),
    FOREIGN KEY (NgayAn) REFERENCES LanAn(NgayAn),
    FOREIGN KEY (MaNS_G) REFERENCES GiaoVien(MaNS_G)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Phong(
	TenPhong VARCHAR(10),
	SucChua INT,
    ChucNang VARCHAR(100),
    PRIMARY KEY (TenPhong)
   ); 
   
CREATE TABLE QuanLy(
	MaNS_C VARCHAR(20),
	TenPhong VARCHAR(10),
	PRIMARY KEY(MaNS_C, TenPhong),
	FOREIGN KEY (MaNS_C) REFERENCES CanBoNhanVien(MaNS_C) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (TenPhong) REFERENCES Phong(TenPhong) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CoSoVatChat (
    TenPhong VARCHAR(10),
    TenVatTu VARCHAR(100),
    SoLuong INT,
    NgayTrangBi DATE,
    TinhTrang VARCHAR(50),
    GiaTri INT,
    FOREIGN KEY (TenPhong) REFERENCES Phong(TenPhong) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY (TenPhong, TenVatTu)
);
